In [4]:
import numpy as np

a = [[30,40,40],[40,30,10]]
arr = np.array(a)

print(arr)
print(arr.shape) #rows, columns
print(len(arr)) #number of nested values
print(np.size(arr)) #number of elements
print(type(arr)) #datatype of variable
print(arr.dtype) #datatype of array
print(arr.astype(float)) #conversion
print(arr.astype(str)) 

[[30 40 40]
 [40 30 10]]
(2, 3)
2
6
<class 'numpy.ndarray'>
int64
[[30. 40. 40.]
 [40. 30. 10.]]
[['30' '40' '40']
 ['40' '30' '10']]
