**Mastering Numpy Array**

NumPy(Numerical Python) is the fundamental package for numerical computation in Python. It provides powerful tools for working with arrays, which are essential for data science, machine learning, and scientific computing.

1. Creting NumPy Arrays:
    - From Lists/Tuples:

In [2]:
import numpy as np

my_list = [1,2,3,4,5]
arr = np.array(my_list)
print(arr)
print(type(arr))    

my_tuple = (1,2,3,4,5)
arr_from_tuple =  np.array(my_tuple)
print(arr_from_tuple)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]


-    
    - Specialized Array Creation:
        - np.zeros(shape) : Create an array filled with zeros.
        - no.ones(shape) : Creates an array filled with ones.
        - np.arange(start, stop, step) : Creates an array with evenly spaced values within a given range.
        - np.linespace(start,stop,step) : Creates an array with num evenly spaced values over a specific interval.
        - np.eye(N) : Creates an identity matrix (a square matrix with ones on the main diagonal and zeros elsewhere). 

In [5]:
zeroes_arr = np.zeros((3,4))
print(zeroes_arr)

ones_arr = np.ones((2,2))
print(ones_arr)

arange_arr = np.arange(0,10,2)   # start at 0 , stop before 10, step by 2
print(arange_arr)

linespace_arr = np.linspace(0,1,5)   # 5 evenly spaced values form 0 to 1
print(linespace_arr)

identity_matrix = np.eye(3)
print(identity_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


2. Array Attributes:
    - ndim : Number of dimensions (axes).
    - shape : Tuple representing the dimensions.
    - dtype : Data type of the elements.
    - size : Total number of elements.

In [7]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.size)

2
(2, 3)
int64
6


3. Array Indexing and Slicing:
    - Similar to lists, but with more powerful multi-dimensional indexing.

In [8]:
arr = np.array([[10,20,30],[40,50,60]])

print(arr[0, 1])    # Output: 20 (element at row 0, column 1)
print(arr[1, :])    # Output: [40 50 60] (all elements in row 1)
print(arr[:, 2])    # Output: [30 60] (all elements in column 2)
print(arr[0:2, 1:3]) # Output: [[20 30],[50 60]]

20
[40 50 60]
[30 60]
[[20 30]
 [50 60]]


4. Array Operations:
    - Element-wise operations: Operations are performed on corresponding elements.

In [9]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(arr1+arr2)
print(arr1*arr2)
print(arr1*2)


[5 7 9]
[ 4 10 18]
[2 4 6]


- 
   - Matrix Operations: Matrix multiplication, dot product, transpose.

In [ ]:
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])
print(np.dot(matrix1,matrix2))  #Matrix multiplication
print(matrix1.T)    #Transpose of a matrix

-   - Universal Functions (ufuncs): Functions that operate element-wise on array (eg, np.sin(), np.exp(), np.sqrt()).

In [4]:
arr = np.array([0,np.pi/2,np.pi])
print(np.sin(arr)) 

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


5. Array Broadcasting:

    - NumPy's broadcasting allows you to perform operations on arrays of different shapes under certain conditions.

In [5]:
arr = np.array([1,2,3])
scalar = 5
print(arr+scalar)

[6 7 8]


6. Array Reshaping and Flattening:
    - reshape(shape): Changes the shape of an array.
    - flatten(): Converts a multi-dimentional array to a 1D array.

In [6]:
arr = np.array([1,2,3,4,5,6])

reshaped_arr = arr.reshape(2,3)
print(reshaped_arr)

flattened_arr = reshaped_arr.flatten()
print(flattened_arr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


7. Random Number Generation:
    - np.random.rand(shape) : Generates random numbers between 0 and 1.
    - np.random.randint(low, high,size) : Generates random integers within a specific range.
    - np.random.normal(mean, stddev, size) : Generates random numbers form a normal distribution.

Assignment/code test:
- Create a 4x4 matrix with random integers between 10 and 50.
- Calculate the mean of each row and each column of the matrix.
- Create a new array containing only the diagonal elements of the matrix.
- Reshape the matrix into a 2x8 matrix.
- Create two 3x3 matrices and perform matrix multiplication on them.

In [51]:
# 1

arr = np.random.randint(10,11,16)
matrix = arr.reshape(4,4)
print(matrix)

# 2

mean_column = np.mean(matrix, axis=0)
print(mean_column)

mean_rows = np.mean(matrix,axis=1)
print(mean_rows)

# 3

arr = np.eye(3,3,0,int)
print(arr)


# 4

arr = np.array([1,2,3,4,5,6,7,8,9,0,11,12,13,14,15,16])
reshaped_arr = arr.reshape(2,8)
print(reshaped_arr)


# 5

matrix1 = np.random.randint(1,10,9).reshape(3,3)
matrix2 = np.random.randint(1,10,9).reshape(3,3)
print(matrix1,"\n second array : \n ",matrix2,"\n the multiple is : \n", matrix1*matrix2)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[10. 10. 10. 10.]
[10. 10. 10. 10.]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[ 1  2  3  4  5  6  7  8]
 [ 9  0 11 12 13 14 15 16]]
[[7 9 8]
 [3 4 6]
 [2 1 1]] 
 second array : 
  [[5 4 7]
 [2 1 1]
 [9 2 2]] 
 the multiple is : 
 [[35 36 56]
 [ 6  4  6]
 [18  2  2]]
