In [7]:
import numpy as np

a = np.array([20,30,40])
b = np.array([30,40,60])
c = np.array([4])
print(a)
print(b)
print(a*b)
print(a*c)


[20 30 40]
[30 40 60]
[ 600 1200 2400]
[ 80 120 160]


In [9]:
a = np.array([40,50,"60"])
print(a)
b = np.array([40,50,60.5])
print(b)

['40' '50' '60']
[40.  50.  60.5]


In [5]:
l1 = [20,30,40]
l2 = 5
print(l1*l2)

[20, 30, 40, 20, 30, 40, 20, 30, 40, 20, 30, 40, 20, 30, 40]


In [10]:
l1= [[20,30],[20,50,60]]
print(l1)
l2 = np.array([[20,30],[20,50,60]])
print(l2)

[[20, 30], [20, 50, 60]]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.