## **Numpy- Creating Arrays, Slicing and Attributes**

#### **Creating**

In [17]:
import numpy as np
arr1 = np.array([[10,20,30,40],[50,60,70,80],[20,40,60,80]])

print(arr)
print(type(arr))


[10 20 30 40]
<class 'numpy.ndarray'>


#### **Slicing**

In [18]:
arr2 = np.array([10,20,30,40])
print(arr2[2:])

print(arr1[0:2,0:3])

print(arr1[0,0:2])

[30 40]
[[10 20 30]
 [50 60 70]]
[10 20]


#### **Attributes**

In [ ]:
print(np.shape(arr1))

print(np.size(arr1))

print(np.ndim(arr1))

print(arr.dtype)

print("hello world")

(3, 4)
12
2
int64
