In [4]:
import numpy as np

arr1 = np.array([30,40,60,20,10])
arr2 = np.array([30,20,10,20,20])

print(arr1+arr2)
print(np.add(arr1, arr2))

[60 60 70 40 30]
[60 60 70 40 30]


In [6]:
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[20,20]])

print(arr1-arr2)
print(np.subtract(arr1, arr2))

[[  0  20]
 [  0 -10]]
[[  0  20]
 [  0 -10]]


In [7]:
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[20,20]])

print(arr1*arr2)
print(np.multiply(arr1, arr2))

[[900 800]
 [400 200]]
[[900 800]
 [400 200]]
