In [4]:
import numpy as np

arr1 = np.array([30,40,60,20,10])
arr2 = np.array([30,20,10,20,20])

print(arr1+arr2)
print(np.add(arr1, arr2))

[60 60 70 40 30]
[60 60 70 40 30]


In [6]:
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[20,20]])

print(arr1-arr2)
print(np.subtract(arr1, arr2))

[[  0  20]
 [  0 -10]]
[[  0  20]
 [  0 -10]]


In [9]:
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[20,20]])

print(arr1*arr2)
print(np.multiply(arr1, arr2))

[[900 800]
 [400 200]]
[[900 800]
 [400 200]]


In [10]:
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[20,20]])

print(arr1/arr2)
print(np.divide(arr1, arr2))

[[1.  2. ]
 [1.  0.5]]
[[1.  2. ]
 [1.  0.5]]


In [15]:
arr1 = np.array([3,4,2,1])
arr2 = np.array([3])

print(np.power(arr1,arr2))

[27 64  8  1]


In [18]:
arr1 = np.array([27, 64,  8 , 1])
print(np.sqrt(arr1))

[5.19615242 8.         2.82842712 1.        ]
