In [4]:
import numpy as np

In [5]:
a = [30.40,50]
b = [5,5,3]
print(a+b)

[30.4, 50, 5, 5, 3]


In [8]:
#Concatinate

arr1 = np.array([[30,40],[10,50]])
arr2 = np.array([[5,5],[7,3]])
print(np.concatenate([arr1,arr2]))

[[30 40]
 [10 50]
 [ 5  5]
 [ 7  3]]


In [18]:
print(np.concatenate([arr1,arr2], axis = 1))
print("-"*35)
print(np.concatenate([arr1,arr2], axis = 0))
print("-"*35)
#horizontal stack
print(np.hstack([arr1,arr2]))
#vertical stack
print("-"*35)
print(np.vstack([arr1,arr2]))

[[30 40  5  5]
 [10 50  7  3]]
-----------------------------------
[[30 40]
 [10 50]
 [ 5  5]
 [ 7  3]]
-----------------------------------
[[30 40  5  5]
 [10 50  7  3]]
-----------------------------------
[[30 40]
 [10 50]
 [ 5  5]
 [ 7  3]]


In [19]:
#split 

a = np.array([20,40,30,40,10,20])
b = np.array_split(a,5)
print(b)


[array([20, 40]), array([30]), array([40]), array([10]), array([20])]


In [20]:
a = np.array([[20,40,30],[40,10,20]])
b = np.array_split(a,5)
print(b)

[array([[20, 40, 30]]), array([[40, 10, 20]]), array([], shape=(0, 3), dtype=int64), array([], shape=(0, 3), dtype=int64), array([], shape=(0, 3), dtype=int64)]
