In [11]:
import numpy as np

In [12]:
a = np.array([[20,40],[60,80]])
print(np.append(a,[90,100]))

[ 20  40  60  80  90 100]


In [13]:
a = np.array([[20,40],[60,80]])
b = np.array([20,40,60,80])
print(np.insert(a,1,50))
print("-"*30)
print(np.insert(b,1,50))

[20 50 40 60 80]
------------------------------
[20 50 40 60 80]


In [14]:
print(np.insert(a,[1,2],[50],axis=0))

[[20 40]
 [50 50]
 [60 80]
 [50 50]]


In [15]:
# deleting data

print(np.delete(a,1))

[20 60 80]
