In [1]:
import numpy as np

In [2]:
# sorting in 1D array
ar = np.array([20,50,70,1,46])
print(np.sort(ar))

[ 1 20 46 50 70]


In [6]:
#Sorting in 2D array
ar2 = np.array([[7,4,2,1,6,9],[6,4,2,8,2,4]])
print(np.sort(ar2))

[[1 2 4 6 7 9]
 [2 2 4 4 6 8]]


In [13]:
# Searching in array

s = np.where(ar == 70)
print(s)

s = np.where(ar%2 ==0)
print(s)

(array([2]),)
(array([0, 1, 2, 4]),)


In [16]:
# Search sorted

ar3 = np.array([1,2,3,4,5,6])
ss = np.searchsorted(ar3,2)
print(ss)

1


In [25]:
# Filter 

ar4 = np.array([20,30,40,50,7])
fa = [True, False, True, False,True]

new = ar4[fa]
print(new)

[20 40  7]


In [26]:
fa = ar4>35
new = ar4[fa]
print(new)

[40 50]


In [27]:
fa = ar4%2==0
new = ar4[fa]
print(new)

[20 30 40 50]
