In [1]:
import numpy as np

In [2]:
a = np.array([20,40,60,70])
print(np.sum(a))

190


In [6]:
# max and min
print(np.min(a))
print(np.max(a))

print(np.size(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.cumprod(a))


20
70
4
47.5
[ 20  60 120 190]
[     20     800   48000 3360000]


In [11]:
a = [100,150,199,200,250,130]
b = [10,50,30,40,30,10]

price = np.array(a)
quantity =np.array(b)

print(price,quantity)

c = np.cumprod([price,quantity], axis = 0)
print(c[1].sum())


[100 150 199 200 250 130] [10 50 30 40 30 10]
31270
